In [3]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [20]:
def mae(y_true,y_predicted):
    total_error = 0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    print('total error is:',total_error)
    mae = total_error/len(y_true)
    print('mae error is:',mae)
    return mae
    

In [21]:
mae(y_true,y_predicted)

total error is: 2.5
mae error is: 0.5


0.5

In [18]:
y_predicted - y_true

array([ 0.7,  0.3, -1. ,  0. ,  0.5])

In [17]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [19]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [30]:
epsilon= 1e-15

In [31]:
y_predicted_new = [max(i,epsilon)for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [32]:
y_predicted_new = [min(i,1-epsilon)for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [33]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [34]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [37]:
def log_loss(y_true,y_predicted):
    epsilon= 1e-15
    y_predicted_new = [max(i,epsilon)for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon)for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [38]:
log_loss(y_true,y_predicted)

17.2696280766844