In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()


In [22]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    digits.data, digits.target, test_size=0.3)


In [24]:

lr = LogisticRegression(max_iter=3000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9537037037037037

In [25]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [26]:
rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9629629629629629

In [31]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=9)

In [32]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[1 2 3 4 5 6 7 8] [0]
[0 2 3 4 5 6 7 8] [1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


In [60]:
def get_score(model,X_train,X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)
def avg(lst):
    return sum(lst) / len(lst)

In [36]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9833333333333333

In [37]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [51]:
scores_l = []
scores_svm =[]
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(C=10),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

C:\Users\tomjo\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\tomjo\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mo

In [61]:
avg(scores_l)

0.9293104410943607

In [62]:
avg(scores_svm)

0.9816192071468453

In [63]:
avg(scores_rf)

0.9437911781127861

In [64]:
from sklearn.model_selection import cross_val_score

In [65]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\tomjo\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\tomjo\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mo

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [76]:
cross_val_score(SVC(C=10),digits.data,digits.target)

array([0.98055556, 0.95833333, 0.98328691, 0.98885794, 0.95821727])

In [70]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93888889, 0.89722222, 0.95264624, 0.96100279, 0.89415042])

In [71]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target)

array([0.93333333, 0.9       , 0.95543175, 0.95543175, 0.92479109])