In [14]:
from imblearn.under_sampling import NearMiss
from imblearn.under_sampling import CondensedNearestNeighbour as CNNb
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN
from collections import Counter
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA,KernelPCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

In [15]:
data = pd.read_csv('Wine.csv')
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values


In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=100)

In [29]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.fit_transform(X_test)
X_train_scaled.shape

(142, 13)

In [30]:
pca_int = PCA(2)
X_train_scaled_pca_int = pca_int.fit_transform(X_train_scaled)
X_train_scaled_pca_int.shape

(142, 2)

In [31]:
pca_percent_to_keep = PCA(0.95)
X_train_scaled_pca_percent_to_keep = pca_percent_to_keep.fit_transform(X_train_scaled)
X_train_scaled_pca_percent_to_keep.shape

(142, 10)

In [32]:
kpca = KernelPCA(n_components=2,kernel='rbf')
Xk_train = kpca.fit_transform(X_train)
Xk_test = kpca.transform(X_test)

In [33]:
lda = LinearDiscriminantAnalysis(n_components=2)
Xl_train = lda.fit_transform(X_train,y_train)
Xl_test = lda.transform(X_test)

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

xs = [Xl_train,Xk_train,X_train_scaled_pca_int,X_train_scaled,X_train]
ys = [y_train,y_train,y_train,y_train,y_train]

for i in range(5):
    print(cross_val_score(LogisticRegression(),xs[i],ys[i],cv=6))

[1. 1. 1. 1. 1. 1.]
[0.41666667 0.41666667 0.375      0.41666667 0.43478261 0.39130435]
[0.95833333 1.         0.875      1.         0.91304348 1.        ]
[0.95833333 1.         0.91666667 0.95833333 1.         1.        ]
[0.95833333 0.95833333 0.875      1.         0.95652174 0.86956522]


C:\Users\tomjo\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\tomjo\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_mo