In [40]:
from imblearn.under_sampling import NearMiss
from imblearn.under_sampling import CondensedNearestNeighbour as CNNb
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN
from collections import Counter
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split


In [41]:
data = pd.read_csv('AID362red_train.csv')
data.head()

NEG_01_NEG  NEG_03_NEG  NEG_04_NEG  NEG_05_NEG  NEG_06_NEG  NEG_07_NEG  \
0           0           0           0           0           0           0   
1           0           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   NEG_03_POS  NEG_04_POS  NEG_05_POS  NEG_06_POS  ...  WBN_LP_H_1.00  XLogP  \
0           0           0           0           0  ...         3.7730  2.704   
1           0           0           0           0  ...         3.5674  2.605   
2           0           0           0           0  ...         3.9847  2.780   
3           0           0           0           0  ...         3.6643  5.239   
4           0           0           0           0  ...         3.6613  4.024   

      PSA  NumRot  NumHBA  NumHBD       MW  BBB  BadGroup  Outcome  
0  119.85       4       6       0  424.569    0         0   Active  
1   94.17      11       8       1  484.593    0         1   Active  
2   77.76       7       5       1  333.384    0         0   Active  
3  119.36       9       8       2  562.659    0         1   Active  
4   76.07       6       6       1  409.482    0         1   Active  

[5 rows x 145 columns]

In [42]:
X = data.drop('Outcome',axis='columns').values
y = data.Outcome.values
y_org = y.copy()

In [43]:
le= LabelEncoder()
y = le.fit_transform(y_org)


In [44]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [45]:
pre_counter = Counter(y_train)

In [46]:
under_nm = NearMiss()
X_nm, y_nm = under_nm.fit_resample(X_train,y_train)
counter = Counter(y_nm)
print(pre_counter)
print(counter)


Counter({1: 2704, 0: 34})
Counter({0: 34, 1: 34})


In [47]:
under_cnnb = CNNb()
X_cnnb, y_cnnb = under_cnnb.fit_resample(X_train,y_train)
counter = Counter(y_cnnb)
print(pre_counter)
print(counter)

Counter({1: 2704, 0: 34})
Counter({1: 188, 0: 34})


In [48]:
over_sm = SMOTE()
X_sm, y_sm = over_sm.fit_resample(X_train,y_train)
counter = Counter(y_sm)
print(pre_counter)
print(counter)

Counter({1: 2704, 0: 34})
Counter({1: 2704, 0: 2704})


In [49]:
over_ada = ADASYN()
X_ada, y_ada = over_ada.fit_resample(X_train,y_train)
counter = Counter(y_ada)
print(pre_counter)
print(counter)

Counter({1: 2704, 0: 34})
Counter({1: 2704, 0: 2690})


In [50]:
X_train.shape

(2738, 144)

In [51]:
y_train.shape

(2738,)

In [58]:
pca = PCA(0.95)
X_pca = pca.fit_transform(X_train)


In [59]:
X_pca.shape

(2738, 2)

In [60]:
xs = [X,X_nm,X_cnnb,X_ada,X_pca]
ys = [y,y_nm,y_cnnb,y_ada,y_train]

from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

for i in range(5):
    print(cross_val_score(DecisionTreeClassifier(),xs[i],ys[i],cv=5))


[0.97518248 0.89343066 0.95912409 0.9751462  0.92105263]
[0.57142857 0.57142857 0.42857143 0.69230769 0.53846154]
[0.77777778 0.82222222 0.79545455 0.72727273 0.72727273]
[0.94717331 0.98053753 0.97775718 0.95829472 0.96753247]
[0.97445255 0.98357664 0.97445255 0.97440585 0.976234  ]
